---
# tasks file for mysql-backup

- name: Install mysql client
  become: yes
  package:
    name: mariadb-client
    state: present

- name: Create backup directory
  become: yes
  file:
    path: "{{ mysql_backup_dir }}"
    recurse: yes
    state: directory
    owner: "{{ mysql_backup_user }}"

- name: Create cron job
  become: yes
  template:
    src: etc-crond-mysql-backup.j2
    dest: /etc/cron.{{ mysql_backup_frequency }}/mysql-backup
    mode: 0755
